const errorMessages = {
  isEmpty: 'error.IS_EMPTY',
  notFound: 'error.NOT_FOUND',
  invalidCredentials: 'error.INVALID_CREDENTIALS',
  exists: 'error.EXISTS',
  somethingWentWrong: 'error.SOMETHING_WENT_WRONG',
  isNotValid: 'error.IS_NOT_VALID',
  isNotString: 'error.IS_NOT_STRING',
  isNotDate: 'error.IS_NOT_DATE',
  isNotNumber: 'error.IS_NOT_NUMBER',
  isNotBoolean: 'error.IS_NOT_BOOLEAN',
  isNotArray: 'error.IS_NOT_ARRAY',
  min: 'error.MIN',
  max: 'error.MAX',
  databaseConnectionError: 'error.DATABASE_CONNECTION_ERROR',
  passwordStrengthFailed: 'error.PASSWORD_STRENGTH_FAILED',
  mismatch: 'error.MISMATCH',
  expired: 'error.EXPIRED',
  requested: 'error.REQUESTED',
  failedToCreate: 'error.FAILED_TO_CREATE',
  failedToFetch: 'error.FAILED_TO_FETCH',
  failedToAdd: 'error.FAILED_TO_ADD',
  failedToUpdate: 'error.FAILED_TO_UPDATE',
  failedToDelete: 'error.FAILED_TO_DELETE',
  failedToSend: 'error.FAILED_TO_SEND',
  lettersOnly: 'error.LETTERS_ONLY',
  notIncluded: 'error.NOT_INCLUDED',
  isEmptyString: 'error.IS_EMPTY_STRING',
  unauthorized: 'error.UNAUTHORIZED',
};

export default errorMessages;
