version: '3.8'

services:
  app:
    build: .
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DATABASE_URL=postgres://ketero:keteropass@db:5432/ketero
      - UPLOAD_DIR=/usr/src/app/uploaded
    volumes:
      - uploaded_volume:/usr/src/app/uploaded
    depends_on:
      - db
    healthcheck:
      test:
        ['CMD-SHELL', 'wget --no-verbose --tries=1 --spider http://localhost:3000/health || exit 1']
      interval: 30s
      timeout: 3s
      retries: 3
    restart: unless-stopped

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ketero
      POSTGRES_PASSWORD: keteropass
      POSTGRES_DB: ketero
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ketero -d ketero']
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  uploaded_volume:
